Update to use latest snapcraft features
morphis/plexmediaserver-snap pull request #3
Opened 2016-11-07 16:15 UTC by sergiusens

Snapcraft now supports debs as sources so there is no need
to wrap around with a `Makefile`.

Additionally, it is better to just dump the directory we want
with the wrapper and use `organize` to make it land in the desired
location.

Signed-off-by: Sergio Schvezov <sergio.schvezov@ubuntu.com>

2016-11-07 16:43 UTC, morphis requested changes

2016-11-07 16:43 UTC, morphis commented on snapcraft.yaml
> +version: 1.2.2.2857-d34b464
Please don't drop -1. That is actually the snap revision number which gets bumped whenever upstream does not change but the packaging.

2016-11-07 16:44 UTC, morphis commented
Small comment inline, otherwise LGTM

2016-11-07 18:53 UTC, sergiusens commented on snapcraft.yaml
> +version: 1.2.2.2857-d34b464
Is it really needed just for packaging? Feels like it comes from the packaging world, very old school.

If it is needed, then we need to duplicate the version entry in the download link which doesn't feel right either.

2016-11-08 06:20 UTC, morphis commented on snapcraft.yaml
> +version: 1.2.2.2857-d34b464
It gives the developer a reference what the snap is build from as we're tagging each snap release to the store in the git repo with <upstream version>-<snap revision>. I agree that we can't use $SNAP_RPOJECT_VERSION then unless we use a regex or so in the source link.

2016-11-08 13:33 UTC, sergiusens commented on snapcraft.yaml
> +version: 1.2.2.2857-d34b464
I've rolled it back but I disagree with the idea of doing this so I will keep my own fork.

2016-11-08 14:01 UTC, morphis commented on snapcraft.yaml
> +version: 1.2.2.2857-d34b464
@sergiusens so what is your approach then to track snap content to git state relationship?

2016-11-17 19:29 UTC, merged